# Generated by Django 5.2.1 on 2025-06-01 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wind_load_analysis_on_hipped_roof', '0003_windloadcalculation_cr_windloadcalculation_qb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windloadcalculation',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='windloadcalculation',
            name='qb',
        ),
        migrations.RemoveField(
            model_name='windloadcalculation',
            name='qp',
        ),
        migrations.RemoveField(
            model_name='windloadcalculation',
            name='vb',
        ),
        migrations.RemoveField(
            model_name='windloadcalculation',
            name='vm',
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='c_direction',
            field=models.FloatField(help_text='Factor accounting for wind direction effects', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Directional Factor (C_direction)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='c_season',
            field=models.FloatField(help_text='Factor accounting for seasonal wind variations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Seasonal Factor (C_season)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='calculation_name',
            field=models.CharField(blank=True, help_text='Optional name for this calculation', max_length=100),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='h_e',
            field=models.FloatField(help_text='Height from ground to the eaves of the roof (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height to Eaves (h_e)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='h_r',
            field=models.FloatField(help_text='Height from the eaves to the roof ridge (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height from Eaves to Ridge (h_r)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this calculation'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='rho',
            field=models.FloatField(help_text='Density of air at the site (kg/m³)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Air Density (ρ)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='terrain_category',
            field=models.CharField(choices=[('0', '0 - Sea or coastal area'), ('I', 'I - Low vegetation'), ('II', 'II - Regular vegetation'), ('III', 'III - Suburban'), ('IV', 'IV - Urban')], help_text="Describes the surrounding environment's roughness", max_length=3, verbose_name='Terrain Category'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='vb0',
            field=models.FloatField(help_text='The 10-minute mean wind speed at 10 m above ground (m/s)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Fundamental Basic Wind Velocity (V_b0)'),
        ),
    ]
