# Generated by Django 5.2.1 on 2025-06-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindLoadCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vb0', models.FloatField(help_text='Basic wind velocity (m/s)')),
                ('c_direction', models.FloatField(help_text='Directional factor')),
                ('c_season', models.FloatField(help_text='Seasonal factor')),
                ('rho', models.FloatField(help_text='Air density (kg/m³)')),
                ('terrain_category', models.CharField(choices=[('0', 'Sea or coastal area'), ('I', 'Lake or flat terrain'), ('II', 'Terrain with low vegetation'), ('III', 'Terrain with regular cover'), ('IV', 'Terrain with numerous and large obstacles')], help_text='Terrain category according to EN 1991-1-4', max_length=3)),
                ('h_e', models.FloatField(help_text='Height to eaves (m)')),
                ('roof_angle', models.FloatField(help_text='Roof angle (degrees)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
