# Generated by Django 5.2.1 on 2025-06-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopitch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindLoadCalculation',
        ),
    ]
