# Generated by Django 5.2.1 on 2025-06-01 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monopitch', '0002_delete_windloadcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindLoadCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vb0', models.FloatField(help_text='The 10-minute mean wind speed at 10 m above ground (m/s)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Fundamental Basic Wind Velocity (V_b0)')),
                ('c_direction', models.FloatField(help_text='Factor accounting for wind direction effects', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Directional Factor (C_direction)')),
                ('c_season', models.FloatField(help_text='Factor accounting for seasonal wind variations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Seasonal Factor (C_season)')),
                ('rho', models.FloatField(help_text='Density of air at the site (kg/m³)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Air Density (ρ)')),
                ('terrain_category', models.CharField(choices=[('0', '0 - Sea or coastal area'), ('I', 'I - Low vegetation'), ('II', 'II - Regular vegetation'), ('III', 'III - Suburban'), ('IV', 'IV - Urban')], help_text="Describes the surrounding environment's roughness", max_length=3, verbose_name='Terrain Category')),
                ('h_e', models.FloatField(help_text='Height from ground to the eaves of the roof (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height to Eaves (h_e)')),
                ('h_r', models.FloatField(help_text='Height from the eaves to the roof ridge (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height from Eaves to Ridge (h_r)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_name', models.CharField(blank=True, help_text='Optional name for this calculation', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this calculation')),
            ],
            options={
                'verbose_name': 'Wind Load Calculation',
                'verbose_name_plural': 'Wind Load Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
