# Generated by Django 5.2.1 on 2025-06-01 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopitch', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windloadcalculation',
            name='building_length',
            field=models.FloatField(default=30.0, help_text='Length of the building parallel to the ridge (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Building Length (L)'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='building_width',
            field=models.FloatField(default=12.0, help_text='Width of the building perpendicular to the ridge (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Building Width (b)'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='effective_height',
            field=models.FloatField(default=0.0, help_text='Height of upwind terrain crest relative to site (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Effective Height of Crest'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='horizontal_distance',
            field=models.FloatField(default=0.0, help_text='Distance from building to crest of upwind terrain (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Horizontal Distance from Crest'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='leeward_openings_area',
            field=models.FloatField(default=0.0, help_text='Total area of openings on leeward face (m²)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Leeward Openings Area'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='parallel_openings_area',
            field=models.FloatField(default=0.0, help_text='Total area of openings on parallel faces (m²)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Parallel Openings Area'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='pitch_angle',
            field=models.FloatField(default=15.0, help_text='Angle of the roof slope relative to horizontal (degrees)', validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(75.0)], verbose_name='Pitch Angle (α)'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='purlin_spacing',
            field=models.FloatField(default=1.2, help_text='Distance between purlins supporting the roof (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Purlin Spacing'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='site_altitude',
            field=models.FloatField(default=0.0, help_text='Elevation of the site above sea level (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Site Altitude'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='structural_factor',
            field=models.FloatField(default=1.0, help_text="Factor accounting for building's dynamic response", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Structural Factor (c_s c_d)'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='truss_spacing',
            field=models.FloatField(default=6.0, help_text='Distance between trusses supporting the roof (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Truss Spacing'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='upwind_slope',
            field=models.FloatField(default=0.0, help_text='Slope of the terrain upwind of the building', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Upwind Slope (φ)'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='upwind_slope_length',
            field=models.FloatField(default=0.0, help_text='Length of the upwind terrain slope (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Upwind Slope Length'),
        ),
        migrations.AddField(
            model_name='windloadcalculation',
            name='windward_openings_area',
            field=models.FloatField(default=0.0, help_text='Total area of openings on windward face (m²)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Windward Openings Area'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='c_direction',
            field=models.FloatField(default=1.0, help_text='Factor accounting for wind direction effects', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Directional Factor (C_direction)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='c_season',
            field=models.FloatField(default=1.0, help_text='Factor accounting for seasonal wind variations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Seasonal Factor (C_season)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='h_e',
            field=models.FloatField(default=3.0, help_text='Height from ground to the eaves of the roof (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height to Eaves (h_e)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='h_r',
            field=models.FloatField(default=3.0, help_text='Height from the eaves to the roof ridge (m)', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height from Eaves to Ridge (h_r)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='rho',
            field=models.FloatField(default=1.25, help_text='Density of air at the site (kg/m³)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Air Density (ρ)'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='terrain_category',
            field=models.CharField(choices=[('0', '0 - Sea or coastal area'), ('I', 'I - Low vegetation'), ('II', 'II - Regular vegetation'), ('III', 'III - Suburban'), ('IV', 'IV - Urban')], default='II', help_text="Describes the surrounding environment's roughness", max_length=3, verbose_name='Terrain Category'),
        ),
        migrations.AlterField(
            model_name='windloadcalculation',
            name='vb0',
            field=models.FloatField(default=21.0, help_text='The 10-minute mean wind speed at 10 m above ground (m/s)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Fundamental Basic Wind Velocity (V_b0)'),
        ),
    ]
