# Generated by Django 5.1 on 2025-05-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('in_wind_depth', models.FloatField()),
                ('width', models.FloatField()),
                ('site_altitude', models.FloatField(default=0)),
                ('terrain_category', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('upwind_slope', models.FloatField(default=0)),
                ('orographic_factor', models.FloatField(default=0)),
                ('structural_factor', models.FloatField(default=1)),
                ('windward_openings', models.IntegerField(default=24)),
                ('leeward_openings', models.IntegerField(default=1)),
                ('parallel_openings', models.IntegerField(default=5)),
                ('windward_area', models.FloatField(default=1.7514)),
                ('leeward_area', models.FloatField(default=37.43)),
                ('parallel_area', models.FloatField(default=1.7514)),
                ('internal_pressure_coeff', models.FloatField(default=0.35)),
                ('basic_wind_velocity', models.FloatField(default=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('area', models.FloatField()),
                ('external_pressure', models.FloatField()),
                ('internal_pressure', models.FloatField()),
                ('net_pressure', models.FloatField()),
                ('net_force', models.FloatField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.windcalculation')),
            ],
        ),
    ]
